### ISSUE TITLE
No local packages or working download links found for pcst-fast==1.0.7

### ISSUE THREAD

**Issue by Laolga** [Shamir-Lab/DOMINO#1]
Hi!
Is seems like the package pcst-fast is not available anymore.  
After running `python setup.py` install I get an error:
```
error: Could not find suitable distribution for Requirement.parse('pcst-fast==1.0.7')
```
And just running `pip install pcst_fast` does not go either:
```
ERROR: Could not find a version that satisfies the requirement pcst_fast (from versions: none)
ERROR: No matching distribution found for pcst_fast
```
Best,
Olga

**Comment by hag007** [comment]
Hi there!

Works fine on my station. Are you run under proper settings (Python 3.6, Linux OS)?

Also, seems like you can get pcst-fast via this link: https://www.wheelodex.org/projects/pcst-fast/

Cheers,
Hagai.

**Comment by Laolga** [comment]
I have Linux, but I'm using Python 3.8. I'm not sure if that's the issue, but maybe pcst_fast is not available for Python 3.8 through pip. 
Either way, I've compiled pcst_fast from their GitHub (using setup.py since make does not work there). Maybe you could test on Python 3.8 and either add the requirement to have Python 3.6 to README or suggest installing pcst_fast from the corresponding GitHub.

Best,
Olga

**Comment by hag007** [comment]
Thanks for your tests and suggestion!

I added "requirement" section to the README + details re the dependency issue.

closing this issue.

**Comment by hag007** [comment]
Thanks for your tests and suggestion!

I added "requirement" section to the README + details re the dependency issue.

closing this issue.
