### ISSUE TITLE
Conda installation does not support Windows

### ISSUE THREAD

**Issue by agitter** [Shamir-Lab/DOMINO#10]
I attempted to install DOMINO through conda with
```
conda create --name domino
conda activate domino
conda install domino -c conda-forge -c bioconda
```
On Windows 10 this failed with
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Package numpy conflicts for:
domino -> numpy=1.18.1
Package networkx conflicts for:
domino -> networkx=2.4
Package statsmodels conflicts for:
domino -> statsmodels=0.11.0
Package python conflicts for:
domino -> python[version='>=3.6,<3.8']
Package pandas conflicts for:
domino -> pandas=1.0.1
Package scipy conflicts for:
domino -> scipy=1.4.1
Package matplotlib-base conflicts for:
domino -> matplotlib-base
Package pcst-fast conflicts for:
domino -> pcst-fast=1.0.7
Package python-louvain conflicts for:
domino -> python-louvain=0.14
```
I assume it is because [pcst-fast](https://anaconda.org/bioconda/pcst-fast) is not available for Windows. It would be helpful to note in the DOMINO readme that the conda install option (and perhaps the entire domino package?) is not Windows-compatible.

Those three `conda` commands worked on a Linux server.

**Comment by hag007** [comment]
Hi agitter,

Pls notice we explicitly mentioned that DOMINO run on Linux OS (under the Requirement section).

**Comment by agitter** [comment]
I see that but interpreted "was tested under" to mean something different from "only works under".
