### ISSUE TITLE
Unclear format for the network file

### ISSUE THREAD

**Issue by Laolga** [Shamir-Lab/DOMINO#3]
Hi! 
Could you please provide an example of the network file or clarify the format here? 
Judging from the error I'm getting the file should have 3 columns: `["node_1", "edge_type", "node_2"]`. What exactly is the edge_type?

Olga

**Comment by hag007** [comment]
Hi there,

The network file format is a simplified sif format, thus, the "edge_type" column (which is not in used by DOMINO). It is now also elaborated in the README
In addition, I also added an example folder with two samples of network files. 

Cheers,
Hagai.

**Comment by Laolga** [comment]
Thanks a lot, everything worked out now.

Best.
Olga
