### ISSUE TITLE
'NoneType' object has no attribute 'subgraph'

### ISSUE THREAD

**Issue by SysMednet** [Shamir-Lab/DOMINO#4]
Hi, I found that there's an error in the main domino.py code.

I used dip.sif in the examples file for the input, and executed the domino command. 

it popped out the following message:
```
File "c:\users\\appdata\local\programs\python\python38\lib\site-packages\domino_python-0.1.1-py3.8.egg\src\core\domino.py",line 59, in create_subgraph
    res = G_modularity.subgraph(list(nodes))
AttributeError: 'NoneType' object has no attribute 'subgraph'
```
How can I solve this problem? thanks!

**Comment by hag007** [comment]
Hi, 

It seems like you're running DOMINO under Windows OS. As mentioned in the README, DOMINO runs only on Linux OS.
If you wish to run DOMINO from Windows, you can do this via the DOMINO website:  http://domino.cs.tau.ac.il/

**Comment by SysMednet** [comment]
Thanks for your reply!
