### ISSUE TITLE
output differences

### ISSUE THREAD

**Issue by BetulCeylan** [Shamir-Lab/DOMINO#5]
Hi!

I run DOMINO consecutively with the same imputs (same network and active genes list) and get different module numbers and sizes. What is the reason behind of this situation? 
When I check the intersection of union of these modules that are produced by seperate run , they have ~80% common genes but the rest of them are different. Which result can we choose or trust in this case?

Thanks,
Betul

**Comment by hag007** [comment]
Hi Betul,

As DOMINO has a probablistic component in it (i.e the first dissection of the network, the PCST step), minor differences among executions are expected. Therefore, getting  ~80% of mutual genes is expexted in some settings (depends on the set of active genes and the network).

Overall, results of different executions usually reflects a similar biological picture (e.g. similar GO term enrichment scores).


Best,
Hagai



Best,
Hagai

**Comment by BetulCeylan** [comment]
Thanks for explanation!
